---
title: "Beta diversity ordinations"
---

```{r, message=FALSE}
library(phyloseq)
library(ggplot2)
library(dplyr)
library(vegan)
```

```{r, message=FALSE}
filepath = "C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 8 Phage therapy and AB in semi-cont/R-analysis/GitHubScripts"
filepath_results = paste0(filepath, "/results/", Sys.Date(), "_")
filepath_figures = paste0(filepath, "/figures/",  Sys.Date(), "_")
ps_exp = readRDS(file = paste0(filepath,"/rawdata/2023-02-02_Phyloseq_object_unnormalised_16srDNA_wo-controls.RDS"))
source(paste0(filepath, "/plot.settings_waterphage.R"))
```

#Bray Curtis 
## Calculate average Bray-Curtis matrix

```{r, message=FALSE}
ps = ps_exp
ps = filter_taxa(ps, function(x) sum(x)>0 , prune = TRUE)
sample_size = 26448 #for DNA, min  sample size
ASV_table = t(as.matrix(ps@otu_table@.Data) ) 
set.seed(3003)
mean_dist = avgdist(x = ASV_table, sample = sample_size, 
        distfun = vegdist, meanfun = mean, 
        iterations = 100, dmethod = "bray", binary = FALSE)

saveRDS(object = mean_dist, file = paste0(filepath_results, "100_iter_Bray_Curtis_dist_DNA.RDS"))
```

### Plot
```{r}
ps = ps_exp
set.seed(3003)
distance = readRDS(file = paste0(filepath, "/results/2023-02-06_100_iter_Bray_Curtis_dist_DNA.RDS"))
ordination_bray = phyloseq::ordinate(physeq = ps, method = "PCoA", distance = distance) 
plot_bray = phyloseq::plot_ordination(physeq = ps, ordination = ordination_bray, 
                                      title = "Bray-Curtis",  axes = c(1,2), justDF = T)
evals1 <- round(ordination_bray$values$Eigenvalues[1] / sum(ordination_bray$values$Eigenvalues) * 100, 2)
evals2 <- round(ordination_bray$values$Eigenvalues[2] / sum(ordination_bray$values$Eigenvalues) * 100, 2)

plot_bray = plot_bray %>%
  dplyr::mutate(Added_Fc7 = case_when(Added_Fc7 == "No" ~ "No-Fc7", 
                                      Added_Fc7 == "Low" ~ "Low-Fc7", 
                                      Added_Fc7 == "High" ~ "High-Fc7")) %>%
  mutate(Added_Fc7 = factor(Added_Fc7, levels = c("No-Fc7", "Low-Fc7", "High-Fc7" )))
BC_DNA = 
ggplot(plot_bray, aes(x=Axis.1, y = Axis.2, fill = Treatment,color = Treatment,  group = interaction(Treatment, Added_Fc7, Rep) ) )  +
  my.theme +
  geom_hline(yintercept = 0, color = "grey28") + 
  geom_vline(xintercept = 0, color = "grey28") +
  #geom_path(alpha = 0.7) +
  ggtitle("Bray Curtis") + 
  geom_point(size = 4, aes(shape = as.character(DPI) , fill = Treatment), color = "black") + 
  scale_shape_manual("DPI", values = c(21,22,23,24, 25)) + 
  guides(fill = guide_legend(override.aes = list(shape = 21 ))) +
  scale_fill_manual(values = treatment_cols1 ) + 
  scale_color_manual(values = treatment_cols1) + 
  xlab(paste("PCoA 1 (", evals1, "%)", sep = "")) +
  ylab(paste("PCoA 2 (", evals2, "%)", sep = "")) + 
  coord_fixed(ratio = evals2/evals1) +
  facet_wrap(~Added_Fc7, nrow = 3) +
  theme(plot.title = element_text(hjust = 0.5)) 
```
#Sørensen
### Calculate average Sørensen matrix
```{r, message=FALSE}
ps =ps_exp
ps = filter_taxa(ps, function(x) sum(x)>0 , prune = TRUE)
sample_size = 26448 #for DNA
ASV_table = t(as.matrix(ps@otu_table@.Data) ) 
set.seed(3003)
mean_dist = avgdist(x = ASV_table, sample = sample_size, 
        distfun = vegdist, meanfun = mean, 
        iterations = 100, dmethod = "bray", binary = TRUE)
saveRDS(object = mean_dist, file = paste0(filepath_results, "100_iter_Sorensen_dist_DNA.RDS"))
```

```{r}
ps = ps_exp
set.seed(3003)
distance = readRDS(file = paste0(filepath, "/results/2023-02-06_100_iter_Sorensen_dist_DNA.RDS"))
ordination_sor = phyloseq::ordinate(physeq = ps, method = "PCoA", distance = distance)
plot_sor = phyloseq::plot_ordination(physeq = ps, ordination = ordination_sor, 
                                   title = "Sørensen", axes = c(1,2), justDF = T) 

evals1 <- round(ordination_sor$values$Eigenvalues[1] / sum(ordination_sor$values$Eigenvalues) * 100, 2)
evals2 <- round(ordination_sor$values$Eigenvalues[2] / sum(ordination_sor$values$Eigenvalues) * 100, 2)

plot_sor = plot_sor %>%
  dplyr::mutate(Added_Fc7 = case_when(Added_Fc7 == "No" ~ "No-Fc7", 
                                      Added_Fc7 == "Low" ~ "Low-Fc7", 
                                      Added_Fc7 == "High" ~ "High-Fc7")) %>%
  mutate(Added_Fc7 = factor(Added_Fc7, levels = c("No-Fc7", "Low-Fc7", "High-Fc7" )))


Sor_DNA = ggplot(plot_sor, aes(x=Axis.1, y = Axis.2, fill = Treatment ) )  +
  my.theme +
  geom_hline(yintercept = 0, color = "grey28") + 
  geom_vline(xintercept = 0, color = "grey28") +
  #geom_path(alpha = 0.7) +
  ggtitle("Sørensen") + 
  geom_point(size = 4, aes(shape = as.character(DPI) , fill = Treatment), color = "black") + 
  scale_shape_manual("DPI", values = c(21,22,23,24, 25)) + 
  guides(fill = guide_legend(override.aes = list(shape = 21 ))) +
  scale_fill_manual(values = treatment_cols1 ) + 
  scale_color_manual(values = treatment_cols1) + 
  xlab(paste("PCoA 1 (", evals1, "%)", sep = "")) +
  ylab(paste("PCoA 2 (", evals2, "%)", sep = "")) + 
  coord_fixed(ratio = evals2/evals1) +
  facet_wrap(Added_Fc7~., nrow = 3) +
  theme(plot.title = element_text(hjust = 0.5)) 
```
